name: flutter_access_refresh_token_manager_demo
description: "Efficiently handle access token expiration with a single request, optimizing performance during concurrent API calls."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true